version: "3.3"
services:
  grafana:
    image: grafana/grafana:7.3.3
    network_mode: "host"
    environment:
      - GF_SERVER_HTTP_PORT=4500
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning/local:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
