version: "3.3"
services:
  grafana:
    image: grafana/grafana:7.3.3
    network_mode: "host"
    environment:
      - GF_SERVER_HTTP_PORT=4500
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
